# Generated by Django 4.2.2 on 2024-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.TextField()),
                ('isbn', models.TextField()),
                ('pubdate', models.DateField()),
                ('mileage', models.IntegerField()),
                ('publisher', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('pricesales', models.IntegerField()),
            ],
        ),
    ]
